API
===

LMM
---

.. autoclass:: glimix_core.lmm.LMM
  :members:
  :exclude-members: value

FastScanner
-----------

.. autoclass:: glimix_core.lmm.FastScanner
  :members:

MTLMM
-----

.. autoclass:: glimix_core.lmm.MTLMM
  :members:
  :exclude-members: value, gradient

Kron2Sum
--------

.. autoclass:: glimix_core.lmm.Kron2Sum
  :members:
  :exclude-members: value, gradient

RKron2Sum
---------

.. autoclass:: glimix_core.lmm.RKron2Sum
  :members:
  :exclude-members: value, gradient